### ISSUE TITLE
Leaflet sidebar-v2 example does not work in Google Chrome 

### ISSUE THREAD

**Issue by jankoc** [Turbo87/sidebar-v2#10]
The sidebar does not open on click when I try the leaflet example:
http://turbo87.github.io/sidebar-v2/examples/index.html

I use Google Chrome version 37.0.2062.124 m. There are no javascript errors reported.

**Comment by ikirmitz** [comment]
The solution by A13xs breaks the library in IE11

**Comment by Turbo87** [comment]
thanks for reporting that @ikirmitz

**Comment by A13xs** [comment]
I tested in Internet Explorer version 11.0.9600.17633 and version 11.0.9600.17691 and working correctly with and without touch screen.

@ikirmitz Can you give more information to reproduce the error?

**Comment by Turbo87** [comment]
I believe this may have been fixed by #35. Please reopen if there are still any issues with the current `master` branch.
