### ISSUE TITLE
generate url when selecting a tab

### ISSUE THREAD

**Issue by d3netxer** [Turbo87/sidebar-v2#101]
I think that some people don't want a url when selecting a tab #9 but for my application I would like to have the url for the tabs display when a tab is selected. This will make it easier to share links that point to specific tabs. 

I tried commenting out the L.DomEvent.preventDefault line in the addTo function in leaflet-sidebar.js but the result is that it is shifting my sidebar. I don't know how to fix it. Any ideas?

**Comment by Turbo87** [comment]
@d3netxer if you want to share links including the document fragment part you would need some additional initialisation code that this library doesn't include. the main asset of this project is the CSS needed for all the mapping libraries, but the JS part of the project should be relatively easy to recreate based on the frontend library/framework you're using, I just happen to include a few simple implementations by default.
