### ISSUE TITLE
The npm|yarn package does not contain all files - js/ol3-sidebar.js missing

### ISSUE THREAD

**Issue by shaula** [Turbo87/sidebar-v2#102]
For whatever reason the npm/yarn package is missing some files?! To be precise js/ol3* files are missing.

See: https://registry.yarnpkg.com/sidebar-v2/-/sidebar-v2-0.3.1.tgz#74e1941124be2aa48a024305a99e36ab3293c23f

**Comment by Turbo87** [comment]
v0.4.0 has the file available, so I'll close this now :)
