### ISSUE TITLE
Sidebar inside a bootstrap container

### ISSUE THREAD

**Issue by moccand** [Turbo87/sidebar-v2#105]
Hi is there a way to have the sidebad adjusted to map height and position when the map is integrated to a bootstraped full page (i use modern-business)

```
<div class="container">
    <div class="row">
        <div class="col-lg-6">
            <h3 class="page-header">
                  My Title
            </h3>
        </div>
    </div>
</div>

<HERE THE SIDEBAR DIVS>

<div id="map" class="sidebar-map"></div>

<div class="container">
    <div class="row">
        <div class="col-lg-6">
        </div>
        <div class="col-lg-6">
        </div>
    </div>
</div>
```

The map is not in a container to get it adjusted to the full screen width.

Thanks,

**Comment by Turbo87** [comment]
you should probably put the sidebar and map into a separate `<div>` and play around with `position: relative`. I'm doing something roughly similar in https://github.com/skylines-project/skylines so it should be possible.
