### ISSUE TITLE
Pass expanded width / and toolbar height as config

### ISSUE THREAD

**Issue by jbaranski** [Turbo87/sidebar-v2#108]
It would be nice to pass a config to control the tab expand width, as well as a config to control the height of the collapsed toolbar.

Like:
```javascript
var sidebar = L.control.sidebar('sidebar', {
    expanded-width: '50px',
    collapsed-height: '100px'
});
```

**Comment by Turbo87** [comment]
That's unfortunately not possible in a reliable way as it would require us to rewrite CSS rules from JS
