### ISSUE TITLE
TypeScript type definitions

### ISSUE THREAD

**Issue by haoliangyu** [Turbo87/sidebar-v2#110]
I wrote a type declaration file for the leaflet sidebar in order to use it in a TypeScript project. I would like to contribute the file and I wonder if it is beyond the purpose of this repo. If so, I may contribute it to [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped).

**Comment by Turbo87** [comment]
@haoliangyu I'm not exactly sure how to integrate them into the repo here, but if you know how a pull request would be very welcome! thanks for working on this! 👍

**Comment by haoliangyu** [comment]
Close as #112 is merged.

**Comment by MaticDiba** [comment]
Hi @haoliangyu,
is there any example of how to use this side bar with typesrcipt? I'm trying to use it with open layers in one of my projects.
