### ISSUE TITLE
Button inside the sidebar to open a featherlight lightbox over the whole page

### ISSUE THREAD

**Issue by Pretobrazza** [Turbo87/sidebar-v2#113]
1. How do I make **a button in a pane** of the sidebar to open a featherlight lightbox over the whole page (map) and not inside the pane? 
2. How do I make **a button of the sidebar** open a featherlight lightbox over the whole page (map) and not inside the pane? 

Thank you for your answer!

**Comment by Turbo87** [comment]
I have never worked with "featherlight lightbox" so unfortunately I have no idea how to answer this either. You could ask your question on stackoverflow.com though and maybe someone there has an answer.
