### ISSUE TITLE
How to initialize sidebar not collapsed by default?

### ISSUE THREAD

**Issue by AntoniBCN** [Turbo87/sidebar-v2#114]
Hello,

I need to initizalize my leaflet map with sidebar not collapsed in order to show several options to users at first view.

It is possible?

Thanks in advance.

**Comment by VictorVelarde** [comment]
Hi,
This could be a duplicate of https://github.com/Turbo87/sidebar-v2/issues/8 
Can't you use something like `sidebar.open(id);` with your default panel?

**Comment by AntoniBCN** [comment]
I'm sorry, I didn't see old issue.

I could use and it works fine !!.

Thanks @VictorVelarde
