### ISSUE TITLE
Angular 4 - Styling

### ISSUE THREAD

**Issue by axhcypod** [Turbo87/sidebar-v2#122]
I had to add :
list-style-type: none; 

to:

`.sidebar-tabs, .sidebar-tabs>ul {
  position: absolute;
  width: 40px;
  margin: 0;
  padding: 0;
}`

with changes:

`.sidebar-tabs, .sidebar-tabs>ul {
  list-style-type: none;
  position: absolute;
  width: 40px;
  margin: 0;
  padding: 0;
}`

to get my icons nice and the sidebar showing things correctly :)
just some fyi to others with the same issue.

btw, nice plugin! thanks dude!

**Comment by Turbo87** [comment]
hmm, that might make sense, yeah. could you open a PR adding that to the SASS files?

**Comment by axhcypod** [comment]
pull request confuse me haha

**Comment by Turbo87** [comment]
Thanks for the reminder :)
