### ISSUE TITLE
Integration with jQuery-UI

### ISSUE THREAD

**Issue by pschweitzerusgsgov** [Turbo87/sidebar-v2#125]
I want to have a search form inside a sidebar panel.  The form works, but the jQuery-UI widgets appear behind the sidebar, and so are not readable, even though they seem to be functional.  

Example: [https://mrdata.usgs.gov/test/map-us.html](https://mrdata.usgs.gov/test/map-us.html)  The search form is accessed using the magnifying glass icon; the two form fields are jQuery-UI autocomplete widgets.  Try "co" in the Commodity field, or "canyon" in the Name field.

Are there some magic words I can plant in the code that will bring those autocomplete widgets to the front?

**Comment by Turbo87** [comment]
you'll probably have to adjust the `z-index` CSS properties of the components

**Comment by pschweitzerusgsgov** [comment]
Success.  Thank you!
