### ISSUE TITLE
Leaflet events propagate to map

### ISSUE THREAD

**Issue by alexlukas** [Turbo87/sidebar-v2#133]
When using a data table in the sidebar, I noticed that clicking and scrolling inside the table propagate to the map. Clicking on an entry or scrolling in the table caused my map view to change.

I put the sidebar inside of the map, as there are other elements on my page and I wanted the sidebar to only be visible inside the map, perhaps this problem only occurs when using the sidebar inside the map div.

As a possible solution, I added an option to disable event propagation to the map and used ``L.DomEvent.stopPropagation``.

**Comment by Turbo87** [comment]
The whole CSS is written under the assumption that the sidebar is not part of the map div, so supporting this is out-of-scope for this project, sorry.

**Comment by alexlukas** [comment]
Okay, that's understandable, I didn't know that. Is there another, recommended way of placing the sidebar inside a non-fullscreen map that doesn't cause problem with event propagation? If not, would you consider a pull request adding a parameter like mentioned in my first post that does not change any behavior if not set to true? I assume using the sidebar in a non-fullscreen environment is a possible use case for others, too.

**Comment by Turbo87** [comment]
you can place the sidebar and the map in another div. at least that's what I'm doing at https://skylines.aero

**Comment by alexlukas** [comment]
I still had to position the sidebar relative to the parent container, because otherwise it was bigger and a little outside the parent, but this worked without any modification to the plugin. Thanks for your quick help!
