### ISSUE TITLE
Sidebar disappear in fulscreen mode

### ISSUE THREAD

**Issue by Jacqbus** [Turbo87/sidebar-v2#134]
There's an issue when turn on fullscreen mode then side panel disappear. Is there any simple solution to prevent that behaviour? I noticed that container with sidebar content isn't in map container, so if it's go fulscreen, left that additional panel behind. I've tried to place panel inside map container, but then i can't interact with it eg. slick buttons, links etc. (i can grab and drag map through it).

**Comment by Turbo87** [comment]
you can put the sidebar and the map in a parent container element and use that to activate fullscreen mode
