### ISSUE TITLE
Example index.html is not working

### ISSUE THREAD

**Issue by TanushN** [Turbo87/sidebar-v2#187]
I have downloaded the repo and launced the index.hml from the examples and it doesn't seem to display correctly.

it shows up as:

<img width="1429" alt="Screen Shot 2020-03-16 at 2 19 25 AM" src="https://user-images.githubusercontent.com/48323276/76732336-2169ea00-672d-11ea-8523-efa599929566.png">

What am I doing wrong?

**Comment by Turbo87** [comment]
It looks like the CSS file hasn't loaded. I can't tell why though. seems to work fine for me here 🤔

**Comment by TanushN** [comment]
Ok, I tried it again in chrome and it worked. I don't know why it doesn't work on safari. Anyways, thx for the help!
