### ISSUE TITLE
Sidebar disappears when viewing the map fullscreen  

### ISSUE THREAD

**Issue by ikirmitz** [Turbo87/sidebar-v2#19]
I've used https://github.com/brunob/leaflet.fullscreen to add a full screen button on my map. Everything works fine when going fullscreen, including all controls placed on the map, except the sidebar. In fullscreen mode it stays behind the map but it still pushes all the other map controls on the left side (including the zoom control) like it's still there.
Is there a way to display the sidebar properly in fullscreen mode?

Many thanks,

Ioannis

**Comment by Turbo87** [comment]
@ikirmitz It might be possible, but only if you modify the fullscreen plugin to not use the `map._container` element for the fullscreen API, but instead the parent node of the sidebar and the map.

**Comment by shaula** [comment]
Its possible with on-board options:
```
var fullscreenControl = new ol.control.FullScreen({
  source: document.getElementById('map').parentNode
});

map.addControl(fullscreenControl);
```

**Comment by aaronwe** [comment]
FYI, in case others stumble across this bug looking for a solution, it appears `source` is now `fullscreenElement` in the plugin. This code works for me in Firefox, but not Chrome, where it properly makes the sidebar go fullscreen, but the map disappears, turning black. I'll update if I find a fix for Chrome.

```
L.control.fullscreen({
    fullscreenElement: document.getElementById('map').parentNode 
}).addTo(map);
```
