### ISSUE TITLE
Bootstrap Header does not allow Bar to stay in map

### ISSUE THREAD

**Issue by alflores-pivotal** [Turbo87/sidebar-v2#20]
When the bar is map under a Bootstrap Header, clicking in "open" makes the bar go to the top again.

**Comment by Turbo87** [comment]
sorry, I don't understand. could you prepare e.g. a [jsfiddle](http://jsfiddle.net/) that shows the problem?

**Comment by onurkose** [comment]
it's just z-index problem of bootstrap. .sidebar class has z-index value of 2000. put a z-index value much higher than this to your .header-wrapper (or whatever else is) class.

**Comment by Turbo87** [comment]
thanks for the solution @onurkose
