### ISSUE TITLE
SIdebar opened when opening website

### ISSUE THREAD

**Issue by kesslerf** [Turbo87/sidebar-v2#217]
Hello,
I am using the sidebar in combination with the ol-layerswitcher and was wondering if it is possible to have the sidebar opened when the website is opened for the first time? 

Thanks,
Felix

**Comment by nathanvda** [comment]
You can open a sidebar pane using the following code: 

     L.control.sidebar('sidebar').open("map-results")

where you refer to the id of the sidebar (`sidebar`) first, and then the id of the pane you want to open (`map-results`). 

I am wondering if you can also immediately render your html to open a pane (e.g. add class `active` to a pane), but I did not test this yet.

**Comment by kesslerf** [comment]
Thanks for the reply, even though I am not using it anymore!
