### ISSUE TITLE
open sidebar in differents panes from js script making click in layer

### ISSUE THREAD

**Issue by pablovg2** [Turbo87/sidebar-v2#23]
I have som js code to open the sidebar with the content of the infowindow, but I cant open the right pane of the sidebar, here is my code

```javascript
 L.control.sidebar('sidebar').open(); //open sidebar
document.getElementById("name").innerHTML = data.name; // I have inside the pane of the sidebar <span id="name"></span>
```

How could I open the right pane of the sidebar?

Thanks

**Comment by alesegdia** [comment]
You can do it by adding the div id as a parameter to open.

**Comment by pablovg2** [comment]
Ok, thanks I think I had problems testing it 

``
L.control.sidebar('sidebar').open("divid"); //open sidebar
``
