### ISSUE TITLE
solution for non-fullscreen maps

### ISSUE THREAD

**Issue by onurkose** [Turbo87/sidebar-v2#24]
Because sidebar v2 has been made for fullscreen maps, it's hard to use smaller maps in pages. If you ever tried, you'd see map controls are moved into middle of your map. Here is temporary solution for this:

1. move your sidebar div into your map div.

2. change this line (.sidebar.collapsed ~ .sidebar-map .leaflet-left) to this (.sidebar.collapsed ~ .leaflet-control-container .leaflet-left)

I told this is temporary because it's not a mobile friendly solution of the problem. It's ok on big screens but you may have problems with mobile views. There can be better way to fix it by the author.

![scrn](https://cloud.githubusercontent.com/assets/139073/7446933/16aafa0a-f1e9-11e4-86c4-c6ced370b7ef.png)

**Comment by Turbo87** [comment]
@onurkose I feel like this is out of scope for this project. As you described, it is mainly meant for fullscreen maps. If you have an idea on how to implement this I'm open to suggestions though.
