### ISSUE TITLE
Android links

### ISSUE THREAD

**Issue by MuellerMatthew** [Turbo87/sidebar-v2#26]
On android devices, when the tab content is longer than the tab, and a user is scrolled down on the page, the first time a user clicks on any links on the tab has the effect of scrolling the tab back to the top of the page. I tested this issue on your examples on a small device using the links to Leaflet and OpenLayers that you have in your examples near the top of your main tabs, and both the Google example and the leaflet example had this scrolling issue, but the Open Layers example did not.

**Comment by Turbo87** [comment]
@MuellerMatthew is this still happening with the current master?

**Comment by MuellerMatthew** [comment]
No, it looks like it is fixed now.

**Comment by Turbo87** [comment]
cool, thanks for the feedback!
