### ISSUE TITLE
Problem with sidebar and Google Earth

### ISSUE THREAD

**Issue by DavidZebris** [Turbo87/sidebar-v2#30]
Hi,
im using this code to add a Google earth layer to my map:
https://github.com/shramov/leaflet-plugins/blob/master/layer/tile/Google.js
(Which works fine without the sidebar)

And I added a sidebar based on the Leaflet-example:
https://github.com/Turbo87/sidebar-v2/blob/gh-pages/examples/index.html
(Which works fine with Open Street Map or Mapquest)

But I get an error when I try to combine both:
The area behind the sidebar (small if closed/collapsed, bigger if opened) is grey and the Google Earth Layer is moved to the right of it.

The Overlay-Layers are not affected by this, so the base map has a wrong position relative to them.

Image with sidebar closed:
![sidebarclosed](https://cloud.githubusercontent.com/assets/8371665/7833760/8f5bea94-0469-11e5-94a1-33e3d1d7aaaa.png)

Image with sidebar opened, the features that used to be in the Serengeti park in the east of Lake Victoria have now moved over the water:
![sidebaropen](https://cloud.githubusercontent.com/assets/8371665/7833761/8f5f6b7e-0469-11e5-9720-7ad54874d385.png)

PS:
If I place the DIV for the sidebar after the Leaflet-Map-DIV (or inside it), the whole area for the open sidebar is always grey (and the Google Earth layer moved), even if the sidebar is closed:
![sidebarclosed2](https://cloud.githubusercontent.com/assets/8371665/7833864/4fc3c2de-046a-11e5-94a6-6795cda2818a.png)

PS2.:
Happens in Firefox, Opera and Chrome.

**Comment by Turbo87** [comment]
sorry, but this problem is out of scope for this plugin. using google maps/earth layers in leaflet is a hack and not officially supported and making it compatible with this plugin is most likely not worth the extra effort. if you find a clean way to fix the problem I'd be happy to review and merge it, but I will not spend time on it myself.
