### ISSUE TITLE
Deep Linking

### ISSUE THREAD

**Issue by MuellerMatthew** [Turbo87/sidebar-v2#33]
The default settings for the sidebar does not allow deeplinking to a particular tab, although the url address is updated when a users selects a tab identify which tab is shown.

**Comment by MuellerMatthew** [comment]
Hello Turbo, 
I have have created a modified sidebar-v2 where I added several additional functions to the sidebar javascript and then modified it so it works in conjunction with https://github.com/mlevans/leaflet-hash, to allow a user to deeplink into both the map and the sidebar using a hash in the url.
Thus for example if the if you wanted to have the map show the profile tab on the sidebar the url would change from: `http://turbo87.github.io/sidebar-v2/examples/index.html`
to 
`http://turbo87.github.io/sidebar-v2/examples/index.html#profile` or `http://turbo87.github.io/sidebar-v2/examples/#profile`
Optionally, if you wanted to have the map move to a new location and zoom instead of the default, you could change the url to:
`http://turbo87.github.io/sidebar-v2/examples/index.html#profile/<zoom>/<lat>/<lng>`
and the map would both open the profile sidebar and change the zoom, and map center.

My question for you is whether you think it would be better to make this into a pull request for the main branch of the sidebar, make it as a small plugin for the sidebar v-2, or since it is a hybrid of 2 existing plugins which are both modified whether you think I should just make it into a freestanding leaflet plugin. 
In the version I am using for my maps i am also adding additional features into the code to also include a feature so the url can trigger a 'click' event on a particular feature within a particular layer by defining several other optional parameters in the url, but i am still testing the code.

**Comment by Turbo87** [comment]
@MuellerMatthew I think doing stuff like that is out of scope for this project. Feel free to build a plugin that uses the other two plugins to do that.
