### ISSUE TITLE
Stacked in mobile

### ISSUE THREAD

**Issue by KrishnaPG** [Turbo87/sidebar-v2#42]
Thank you for sharing this very good work. It is helpful.

One question: In the mobile mode, the sidebar is "covering up" the map (hovering on top it). Would it be possible to make sidebar go above / below the map (in the mobile mode) so that both map and sidebar content can be viewed simultaneously (at-least partially).

The reason I am asking is, I have objects moving on the map, while their related info (such as speed etc.) are present in the sidebar. This works great in the desktop mode, to display info side-by-side with moving objects on the map. In the mobile mode, the map disappears below the sidebars. Thought it would be great if the sidebar instead of covering up the map, goes above / below the map (like in typical bootstrap grid system).

**Comment by Turbo87** [comment]
you should be able to prevent this by setting the `threshold-sm` variable in https://github.com/Turbo87/sidebar-v2/blob/master/scss/_base.scss#L3 to 0px, but due to the narrow screens on those mobile devices I'd highly recommend rethinking the user interface instead.
