### ISSUE TITLE
maps only ?

### ISSUE THREAD

**Issue by jmls** [Turbo87/sidebar-v2#44]
Browsing through this library, I am slightly confused (doesn't take much) - is this a sidebar for *any* js app, or is it for maps only ? Is the maps-specific css just so that it can blend in better ? 

Also, can panels appear stacked (like a toolbox) rather than tabbed (ie one at a time)

Finally - has anyone got / done / know of a material-theme for the sidebar ?

thanks

**Comment by Turbo87** [comment]
> is this a sidebar for any js app, or is it for maps only ?

it was written primarily for maps, but in theory you could also use it in a more generic way

> Is the maps-specific css just so that it can blend in better ?

yes

> can panels appear stacked (like a toolbox) rather than tabbed (ie one at a time)

no, that functionality is not implemented

> has anyone got / done / know of a material-theme for the sidebar ?

I don't know of any such theme, but it should be relatively easy to implement using the SASS files
