### ISSUE TITLE
right panel for openlayers

### ISSUE THREAD

**Issue by hizperion** [Turbo87/sidebar-v2#46]
i think the .sidebar('sidebar', {position: 'right'}) doesn't work in openlayers example. how do i make it work in openlayers?

**Comment by Turbo87** [comment]
from what I remember I tested it with the openlayers map too so this is most likely a bug. feel free to debug it and send a fix if you can.

**Comment by nikitul** [comment]
Is working, but the command is a little different for openlayers example. Try this:
```javascript
var sidebar = $('#sidebar').sidebar({position: 'right'});
```

**Comment by hizperion** [comment]
yeahhh it's working, thanks a lot!
