### ISSUE TITLE
Typo in bower.json?

### ISSUE THREAD

**Issue by restani** [Turbo87/sidebar-v2#48]
Hi! I'm just starting to use sidebar with bower and was wondering if there wasn't an issue with bower.json:

  "main": [
    "css/gmaps-sidebar.js",
    "css/leaflet-sidebar.js",
    "css/ol2-sidebar.js",
    "css/ol3-sidebar.js",
    "js/jquery-sidebar.js",
    "js/leaflet-sidebar.js"
  ],

Shouldn't the css files be with .css instead of .js ?

**Comment by Turbo87** [comment]
that would certainly make more sense, yes! :D

could you open a pull request fixing the problem?

**Comment by restani** [comment]
Will do!

**Comment by Turbo87** [comment]
resolved by #49
