### ISSUE TITLE
Better Error Handling?

### ISSUE THREAD

**Issue by 1parkplace** [Turbo87/sidebar-v2#52]
Would it be hard to add some better error handling for when the sidebar div is not present?

It should check if the sidebar HTML is present and if not, just return out.  Right now, if the DIV isn't present, it causes Mapbox/Leaflet to throw errors and the map is not able to be initialized.

Any ideas?

**Comment by Turbo87** [comment]
that should probably be possible, feel free to sketch something out in a pull request!
