### ISSUE TITLE
Remember scrolling position when switching tabs

### ISSUE THREAD

**Issue by neothemachine** [Turbo87/sidebar-v2#54]
When a tab pane is long and thus has scrollbars it would be nice to remember that scrolling position when switching to another tab and then back again. Would this be an easy fix?

**Comment by Turbo87** [comment]
I guess it's possible, but I'm not sure if everyone would want that behavior. Feel free to implement it but make sure to use an option like `rememberScroll: true` in the options.

**Comment by neothemachine** [comment]
I noticed that Chrome remembers the position, whereas Firefox and IE forget them. I wonder what the correct behavior is supposed to be from a standards perspective. I won't spend time looking into this I think, at least until someone complains in my app about that.

**Comment by Turbo87** [comment]
Okay, thanks for investigating. I think fixing browser inconsistencies is out of scope for this plugin. If anyone finds a simple solution for this I'd be happy to merge, but I won't work on it myself either. Closing this for now.
