### ISSUE TITLE
npm install fails

### ISSUE THREAD

**Issue by andywer** [Turbo87/sidebar-v2#55]
Hi there!
I just recognized that `npm install sidebar-v2` fails. Is the package not published?

Cheers

**Comment by Turbo87** [comment]
sorry for the long time to respond. you are correct, the project is (at least not yet) published on npm.

the `package.json` file in this repository is primarily meant for installing the `gulp` project builder for compiling the SASS files, but not for publishing the project.

npm usually expects projects to follow a certain modules structure, but neither of the two sidebar implementations in this project is compatible with that. also I'm not sure how npm handles SASS/CSS files at the moment. all in all I don't see the benefit of publishing the project to npm at the moment, but feel free to give my some good counter-arguments.
