### ISSUE TITLE
Position sidebar on right side?

### ISSUE THREAD

**Issue by rbarkas** [Turbo87/sidebar-v2#6]
I'd like to place a sidebar on the right side of the screen.
I've tried
    L.control.sidebar('sidebar', {position: 'topright'})
But that doesn't work.
I've tried re-ordering the divs but that didn't work either.

How can I move the sidebar to the right side?

**Comment by humitos** [comment]
It would be awesome to have something like `{position: "right"}` or something like that. Let me know if I can help in some way to do that (I've been checking the code but I'm not sure how to do it yet)

**Comment by netsgnut** [comment]
I am looking to the same on Leaflet as well. At first glance I think it will take a few lines of CSS and some small changes on JS. Not entirely sure how to achieve that on OpenLayers and Google Maps, though.

**Comment by ashu-galaxy** [comment]
when I open sidebar on button click map also moving along with the sidebar. only sidebar should open map should not move how to fix this please help...
