### ISSUE TITLE
Dynamically add panes?

### ISSUE THREAD

**Issue by JamesRamm** [Turbo87/sidebar-v2#64]
Hi
I am trying to dynamically add panels to a sidebar instance. 
I am using JQuery to create a `".sidebar-pane"` `div` and append this to the `".sidebar-content"` div.
I also create an `<a>` with the `href` set to the id of the `sidebar-pane` and the `role` set to `tab`. I append this to `<ul>` list under the `sidebar-tabs` `div`. 

All in all, the markup looks correct, and the button appears on the sidebar. 
However, it doesn't respond to any click events (the sidebar panel does not show). Is there anything I need to do to get the click event to register, or is there a better way of dynamically inserting new panes?

Thanks for your help!

**Comment by Turbo87** [comment]
#43 implements something like this, but only for the leaflet version. I personally don't have a use case for this, so I won't spend any time on it myself, but I'd be happy to review and merge any pull requests in that direction.

**Comment by noerw** [comment]
To achieve this, you need to add a click listener to your `<a>` tag like this.

    var sidebar = $('#sidebar').sidebar();

    // ...

    $('a').click(function() { // change the selector to your needs
        sidebar.open(this.attr('href').slice(1)); // assuming the href contains a hash only
    });

This is and more is nicely wrapped in an API in [my fork](https://github.com/noerw/sidebar-v2).

@Turbo87 Well, the pullrequest is there. I can rebase it onto master in the next weeks, if interested

**Comment by Turbo87** [comment]
@noerw am I wrong that the PR only contains the changes for the leaflet JS files?

**Comment by noerw** [comment]
indeed, the jquery version still needs to be done.
I didnt do this at that time, as porting the changes wouldnt be trivial, if i remember correctly
I'll see if I do this, but this will take some time

**Comment by JamesRamm** [comment]
@noerw Thanks - great work, this is more or less what I was looking for! 
I have a couple of suggestions:

The `data.pane` attribute is handled differently depending on whether it is string or DOM element (line 220):
```
if (typeof data.pane === 'string') {
            // pane is given as HTML string
            pane = L.DomUtil.create('DIV', 'sidebar-pane', this._paneContainer);
            pane.innerHTML = data.pane;
        } else {
            // pane is given as DOM object
            pane = data.pane;
            this._paneContainer.appendChild(pane);
        }
```

I think this is a little misleading - why should it assume that the `sidebar-pane` div is _not_ part of the string, yet _is_ part of the dom object? I think it should either:

- always assume that it needs to create the `sidebar-pane` div (as this is required for the panel to function properly and we want the user to worry about their actual content and not divs like this)
- Or check whether the string/object contains a `sidebar-pane` div and treat it accordingly. 

It would also be good if the `data` could contain an optional `header` attribute. This could just be a text title for the panel, in which case the function would create a `sidebar-header`: 

```
'<h1 class="sidebar-header">'+title+'<div class="sidebar-close"><i class="fa fa-caret-left"></i></div></h1>'
```
(ofc, this makes assumptions on font awesome)
or an element describing a custom header. 

The header would be appended to the `sidebar-pane` right before the `data.pane` content gets added

**Comment by Turbo87** [comment]
as mentioned in https://github.com/Turbo87/sidebar-v2/pull/43#issuecomment-257585182 I'm not planning to support dynamically adding/removing panels from the sidebar in this library. it should however be possible to build something on top of it that handles this.
