### ISSUE TITLE
Make the first item open when the page loads.

### ISSUE THREAD

**Issue by rogerhnn** [Turbo87/sidebar-v2#66]
How can I make the first item of the sidebar opened by default?
Thanks

**Comment by Turbo87** [comment]
you can use the `open()` method of the sidebar to open tabs programmatically

**Comment by rogerhnn** [comment]
Can you please point me where I need to add this? I am using the leaflet version.
In your example can you point me where in the code I need to add and what? I am new to these things.

Appreciate the help, thanks

**Comment by Turbo87** [comment]
it should work like this:
```js
var sidebar = L.control.sidebar('sidebar').addTo(map);

// open the sidebar-pane with id="messages"
sidebar.open('messages');
```
