### ISSUE TITLE
Zoom in/out control stop moving when the sidebar is below the control

### ISSUE THREAD

**Issue by corinat** [Turbo87/sidebar-v2#67]
Hello,

Is it posibile to make the zoom in/out control not to move when clicking on the sidebar? I would like to make this posible when the sidebar si small and below the zoom in/out control.

Thanks,
Corina

**Comment by Turbo87** [comment]
with some CSS tweaking this might be possible. it should be easy enough for OpenLayers, but probably harder for Leaflet and Google Maps due to the way their controls work. I can't tell you exactly how to do it though.

**Comment by corinat** [comment]
I'm using it with Leaflet and yes I was thinking that CSS will help in this case, but I didn't find a solution until now. Thanks anyway.
