### ISSUE TITLE
Add text to sidebar

### ISSUE THREAD

**Issue by davidr-halomicrosystems** [Turbo87/sidebar-v2#72]
Hi there, firstly just a major thanks for such a beautiful sidebar!

As per the following image you can see we are trying to go for a very flat design and editing some of the css we have semi achieved this 👍  http://postimg.org/image/y6hfg7mpt/

However we would like to add some other content along the sidebar-tabs, in particular some text. See the following picture for a rough idea http://postimg.org/image/t8rgbzvep/

The dividers I guess would be cool but nothing major for now.

**Comment by davidr-halomicrosystems** [comment]
Ignore me re dividers. As per image its now looking great with a transparent sidebar http://postimg.org/image/rhg8iy2gx/

I guess all that is needed is some way of making the width larger?

**Comment by noerw** [comment]
looks great!
would you mind providing your style to the sidebar, as an alternative styling? i think this would be a great enhancement

**Comment by davidr-halomicrosystems** [comment]
@noerw Thanks! 👍 will look at adding the styling/html here tomorrow

**Comment by Turbo87** [comment]
@davidr-halomicrosystems the sidebar is currently not designed to support adding text to the icons, sorry.
