### ISSUE TITLE
Linking sidebars

### ISSUE THREAD

**Issue by rogerhnn** [Turbo87/sidebar-v2#78]
How can I link sidebars in a way that when I go to the url http://turbo87.github.io/sidebar-v2/examples/index.html#profile the Profile tab will be open?

**Comment by noerw** [comment]
```js
window.onhashchange = function() {
  sidebar.open(window.location.hash.slice(1));
};
```
should do the job

**Comment by rogerhnn** [comment]
Thanks, it worked perfectly!
