### ISSUE TITLE
Firefox Mobile Android 48.0

### ISSUE THREAD

**Issue by Dr-Mx** [Turbo87/sidebar-v2#79]
My phone just updated to the newest version of Firefox, and now sidebar-v2 has completely stopped working.  I wondered if anyone else was having the same issue?

Trying to debug the issue in a remote console, I received:

```
TypeError: t.originalEvent is undefined
    o.DomEvent._filterClick()
    o.DomEvent.addListener/s()
```

edit: this error is coming from leaflet.js

**Comment by Turbo87** [comment]
Can you check if updating leaflet is fixing things?

**Comment by Dr-Mx** [comment]
Yes, this may be related: https://github.com/Leaflet/Leaflet/pull/4256
Will test tomorrow.

**Comment by Dr-Mx** [comment]
The newer pre-release candidates do indeed fix the issue.  Not sure if 0.7.7 will be updated, but can be easily edited to reflect the fix.

```
var i = t.timeStamp || (t.originalEvent && t.originalEvent.timeStamp)
```
