### ISSUE TITLE
Sidebar v2 without a map

### ISSUE THREAD

**Issue by rogerhnn** [Turbo87/sidebar-v2#80]
Hi, if I want to use sidebar v2 without a map, just an image as background how can I do that? I tried removing leaflet but I think it depends on it.
How can I make it work without leaflet?
Thanks

**Comment by Turbo87** [comment]
you can use the jQuery version and as long as you have a sidebar-map div it should work. I have never tried it though...

**Comment by atlasdatabase** [comment]
it doesn't seem to work, or I am doing something wrong.

I am trying with the example in your examples folder index.html
I removed all the leaflet related files from the index.html code, and changed it to use jquery-sidebar.js
