### ISSUE TITLE
Can No Longer Close Sidebar After Making It Resizable

### ISSUE THREAD

**Issue by sarcanon** [Turbo87/sidebar-v2#81]
Hello.
I'm trying to make my sidebar resizable using JQuery UI's Resizable interaction. I do this as follows:
```
  $( function() {
    $( "#sidebar" ).resizable();
  } );
```
However, while this does succeed in making the sidebar resizable, I can no longer collapse it. I.e., clicking on the close icon after resizing the sidebar has no effect. Interestingly, if I do not resize the sidebar, clicking the close icon will correctly close it. So it seems once the sidebar gets resized, the close icon is rendered inactive.
I've traced the code in the debugger, but I'm not sufficiently familiar with JS and JQuery to determine what the problem is.
Thanks for any assistance you can provide.

**Comment by Turbo87** [comment]
Sorry, I've never used that plugin and it seems that they are simply not compatible with each other. I don't think there is much I can do about it at this point.

**Comment by jb2b38** [comment]
The problem is not related to JQuery UI plugin, as I have the same problem with a classic resize:
$('.sidebar').width('677px');
Changing the size affects the component's behaviour, except if you only change the size from CSS, but then you cannot resize it at runtime, which is not convenient.

**Comment by sarcanon** [comment]
Hi, Tobias.

So, does jb2b38's observation change anything?

I would love really love to be able to resize the sidebar. It so perfectly
suits my project in every other way.

Thanks!

- Scott

**Comment by Turbo87** [comment]
the problem is that jQuery is setting the width on the element itself and that overrides any width specified on the attached CSS classes. since this plugin is using CSS classes to resize/open/close the sidebar those two approaches are unfortunately not compatible. feel free to explore options to make them compatible though, I'm not saying that it's impossible.
