### ISSUE TITLE
Is it possible to use the widget in an embedded setting (not only a full screen map)?

### ISSUE THREAD

**Issue by sdlime** [Turbo87/sidebar-v2#82]
Would love to use this with an embedded map that is also outfitted with a full screen plugin. 

However, by default it seems to always anchor itself to the left/right area of the whole window. If I define the sidebar elements within the map div it shows up in the right place but doesn't alter the position of existing map controls as it does in the demo - the sidebar obscures them.

I also noticed that if you take the leaflet example and change the order of the sidebar and map divs on the page (so the map is first) then existing map control positions are not altered to account for the sidebar. I imagine both of these issues are related.

 Example: [http://www.dnr.state.mn.us/maps/compass-leaflet-sidebar-v2.html](url)

**Comment by Turbo87** [comment]
@sdlime it should be possible to use it like that if you wrap the sidebar and map in a div and use that for the fullscreen plugin. keep in mind though that the responsive CSS breakpoints are optimized for full screen usage and it might look bad if the map is significantly smaller than that.

**Comment by sdlime** [comment]
That suggestion works but this setup isn't compatible with the MapBox full screen plugin.
