### ISSUE TITLE
NPM package

### ISSUE THREAD

**Issue by JamesRamm** [Turbo87/sidebar-v2#83]
Would be good to make sidebar-v2 available on NPM so you can e.g. `npm install sidebar2`

**Comment by Turbo87** [comment]
thanks for reminding me! I guess by now I'm convinced that publishing on NPM makes sense. 👍

**Comment by despirados** [comment]
Of course it does, we are just waiting for that, many thanks ;)

**Comment by Turbo87** [comment]
https://www.npmjs.com/package/sidebar-v2
