### ISSUE TITLE
https versions of examples don't work

### ISSUE THREAD

**Issue by rrooij** [Turbo87/sidebar-v2#89]
If the https version of GitHub pages is used, Leaflet won't be loaded since the CDN makes use of http instead of a secure https connection.

Steps to reproduce:

1) Visit: https://turbo87.github.io/sidebar-v2/examples/index.html
2) Leaflet won't load

**Comment by Turbo87** [comment]
@rrooij actually it seems that the CDN is using a HTTPS connection, but somehow the certificate isn't matching the domain. I guess we could just use the URLs provided by https://cdnjs.com/libraries/leaflet/0.7.2 instead. Could you prepare a PR to change those URLs?

**Comment by jbelien** [comment]
Leaflet quickstart guide (http://leafletjs.com/examples/quick-start/) mentionned these URL's :
https://unpkg.com/leaflet@1.0.1/dist/leaflet.css
https://unpkg.com/leaflet@1.0.1/dist/leaflet.js
