### ISSUE TITLE
Avoid using href for choosing tabs.

### ISSUE THREAD

**Issue by slauyama** [Turbo87/sidebar-v2#9]
Hi there,

I was having an issue with working with href attribute. The href attribute modifies the url and can mess up any routing that I had set up. So to avoid breaking my routing, Instead of doing
```
<ul class="sidebar-tabs" role="tablist">
    <li><a href="#home" role="tab"><i class="fa fa-bars"></i></a></li>
    <li><a href="#profile" role="tab"><i class="fa fa-user"></i></a></li>
    <li><a href="#messages" role="tab"><i class="fa fa-envelope"></i></a></li>
    <li><a href="#settings" role="tab"><i class="fa fa-gear"></i></a></li>
</ul>
```
I made the html look like this.
```
<ul class="sidebar-tabs" role="tablist">
    <li><a data-tab="#home" role="tab"><i class="fa fa-bars"></i></a></li>
    <li><a data-tab="#profile" role="tab"><i class="fa fa-user"></i></a></li>
    <li><a data-tab="#messages" role="tab"><i class="fa fa-envelope"></i></a></li>
    <li><a data-tab="#settings" role="tab"><i class="fa fa-gear"></i></a></li>
</ul>
```
Then i had to change some of the js. Replacing all calls getting the hash to getting dataset.tab.
So this worked as a quick fix but I'm not sure if it is the best idea. All <a> tags should have an href so the html tags should probably be changed if you remove the href. 

Maybe it would work better if you pass it in as an option to the leaflet-sidebar? I'm not sure if you have any thoughts on this but I thought it was interesting.

**Comment by chegga** [comment]
Looks good but does not working in IE <= 10 (dataset is not supported).
But it is easy to make it working. Just change
```javascript
child.firstChild.dataset.tab
```
into
```javascript
child.firstChild.getAttribute('data-tab')
```

and

```javascript
this._sidebar.open(this.firstChild.dataset.tab.slice(1));
```
into
```javascript
this._sidebar.open(this.firstChild.getAttribute('data-tab').slice(1));
```

**Comment by Turbo87** [comment]
I think this should be fixed in the current `master` branch. I'm still using the `href` attribute, but the URL is no longer modified.
