### ISSUE TITLE
Specify sidebar-pane width

### ISSUE THREAD

**Issue by kortos** [Turbo87/sidebar-v2#90]
Hello,
is it possible to change the width of a specific sidebar-pane?

Best regards and thank you for that great sidebar tool :-)
Matthias

**Comment by Turbo87** [comment]
you can change the widths at https://github.com/Turbo87/sidebar-v2/blob/master/scss/_base.scss#L5-L8 but you'll have to recompile the SASS files to CSS afterwards. there is no way to modify those widths dynamically from javascript though.
