### ISSUE TITLE
Sidebar-v2 + Bootstrap (with header and container-fluid)

### ISSUE THREAD

**Issue by jbelien** [Turbo87/sidebar-v2#91]
Hi, 

Sidebar-v2 project is really awesome but I'm struggling when I try to combine the sidebar with Bootstrap using a fixed header and a container-fluid.

Here is an example : http://codepen.io/anon/pen/ALdBGR

I suppose the problem comes from using `position: absolute;` ! Is there an easy way to place the sidebar inside the container and limit the sidebar to the container ?

Thanks.

**Comment by Turbo87** [comment]
@jbelien it is definitely possible, but on first glance I'm not sure what you're doing wrong. Have a look at e.g. https://skylines.aero/flights/60985/ where we're doing something similar.

**Comment by jbelien** [comment]
@Turbo87 : Thanks a lot ! I'll look at it 👍
