### ISSUE TITLE
Create a Grunt Version and improve the SCSS files?

### ISSUE THREAD

**Issue by douglasdeodato** [Turbo87/sidebar-v2#95]
Hi,

I would like know if I can contribute in that project doing  a Grunt Version and improve the SCSS files?

thank you.

**Comment by noerw** [comment]
What do you need grunt for?
For minification etc, we could merge some of this fork: https://github.com/JamesRamm/leaflet-sidenav
Besides making it leaflet only - James created a npm package, which has scripts for such development tasks:
```
"lint": "jslint js/leaflet-sidenav.js",
"build-css": "node-sass --include-path scss scss/leaflet-sidenav.scss dist/leaflet-sidenav.css",
"minifyjs": "uglifyjs js/leaflet-sidenav.js -o dist/leaflet-sidenav.min.js",
"minifycss": "cleancss -o dist/leaflet-sidenav.min.css dist/leaflet-sidenav.css",
"prepublish": "npm run build-css && npm run minifyjs && npm run minifycss"
```

**Comment by Turbo87** [comment]
@douglasdeodato while I'm not a huge fan of gulp either, porting this to grunt doesn't seem to have any obvious advantages. what are you planning to improve in the SCSS file?

**Comment by douglasdeodato** [comment]
@noerw @Turbo87 , the idea to have grunt is make more comfortable for someone who don't use gulp, I think if we have 2 options can be more fair and easy for someone test and develop.

Create a grunt version will not implicate in anything in the code, we just will have few more packages to be installed by npm, this was suggestion if you think this is not important  no problem.


@Turbo87  about scss I was trying more organize the code and structure, making some palettes for colors reducing many variables,  create some mixins and functions to reduce the code and organize more.

I am not saying the code there is bad I just want organize it and make clean and easy understandable for the next generations .

also I want create a documentation just for the SCSS, so next developers can easy collaborate on it.

I here to help and I hope you let me do this.

thanks all, have a nice week.

**Comment by Turbo87** [comment]
@douglasdeodato sorry, but I don't think it's useful to have two build systems in the same project. there might be other who would like to use broccoli, others who want to use brunch, ...

I'm not sure yet I understood what you want to change about the SCSS files, but feel free to open up a PR with some changes and I'll try to find the time to review then.

**Comment by Turbo87** [comment]
closing this in favor of any upcoming PRs to the SCSS files
