### ISSUE TITLE
Missing js/ol3-sidebar.js in npm repository

### ISSUE THREAD

**Issue by sushicodeur** [Turbo87/sidebar-v2#98]
Hello, 

I've installed sidebar-v2 using npm, like so : npm install --save sidebar-v2

But ol3-sidebar.js (and its minified version) are missing from what have been installed. It looks like the same files are also missing from the zip file of the github v0.3.1 release.

It looks like it could solve the problem to create a new release including these files.

Many thanks.

**Comment by Turbo87** [comment]
@sushicodeur `ol3-sidebar.js` will be included in the upcoming v0.4.0 release. you can always use `npm install --save github:Turbo87/sidebar-v2` in the meantime to install the latest version via git instead.

**Comment by sushicodeur** [comment]
Oops, looks like I missed your answer :/

Thank you, I'll try that instead and wait for 0.4.0 :)
