### ISSUE TITLE
Allow the ability to pass a document fragment to control

### ISSUE THREAD

**Issue by roemhildtg** [Turbo87/sidebar-v2#99]
Rather than passing the element id, would it be possible to pass a [document fragment](https://developer.mozilla.org/en-US/docs/Web/API/DocumentFragment) to the sidebar control? 

I could make a pull request if this is something I can get working and you would accept.

**Comment by Turbo87** [comment]
I don't understand. Why don't you just attach that fragment to the content div?

**Comment by roemhildtg** [comment]
It was a passing thought, sorry I figured out I could do it that way also.
